# Generated by Django 4.2.27 on 2026-01-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landmark',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
