# Generated by Django 4.2.27 on 2026-01-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_landmark_summary_landmark_wikidata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarkprediction',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
