# Generated by Django 4.2.27 on 2026-01-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_landmarkimage_trainingrun_tripplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='image_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
