# Generated by Django 4.2.27 on 2026-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_trainingrun_image_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmarkprediction',
            name='distance_km',
        ),
        migrations.AlterField(
            model_name='landmarkimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='TripPlan',
        ),
    ]
